### ISSUE TITLE
Range Check Error in GenerateHash(); Integer Overflow Exception

### ISSUE THREAD

**Issue by SamJokO** [viniciussanchez/bcrypt#4]
TBCrypt.GenerateHash() function raise 'Range Check Error'.

In source TBCryptImpl.MakeSalt: TBytes
while I <= Length(LRandomTemp) do
begin
   ...
end
It should be change like this
I < Length(LRamdomTemp)

And, also i added {$Q-} top of BCrypt.Core.pas
because,
TBCryptImpl.Encipher(var lr: array of DWORD; const AOffset: Longint);
function raise exception Integer Overflow exception
N := DWORD(N + FSBox[$100 or ((LBlock shr 16) and $FF)]); 
stop this line.

Thank you

**Comment by viniciussanchez** [comment]
I tried to simulate the problem and I couldn't. Could you give me more information? Delphi version? Are you using the sources of the last released release? What is the password used to generate the problem?

**Comment by hugosiscom** [comment]
Estou com o mesmo problema,
mas o problema só acontece quando é executado como serviço do Windows,
modo console vai normal.

senha bd hash:     $2a$10$AWuZ3mfQsGn4m863QnOER.CuAa9eRn1mRDRnjp/.NSpWLJrhTwJT6

 if (TBCrypt.CompareHash(Req.Body<TJSONObject>.GetValue<string>('password'),LService.qryPesquisapassword.AsString))  
    then
  begin
  end;

provoca erro : Integer overflow

**Comment by viniciussanchez** [comment]
@hugosiscom  Qual a versão do Delphi? Está usando a última versão liberada? Qual a senha usada para teste?

**Comment by hugosiscom** [comment]
Delphi 11.1

bcrypt 1.0.3
