### ISSUE TITLE
Bcrypt  "error": "Range check error"

### ISSUE THREAD

**Issue by Iaster** [viniciussanchez/bcrypt#5]
depurando o projeto cheguei na procedure TBCryptImpl.MakeSalt.  No bloco :-

  while I <= Length(LRandomTemp) do
  begin
    LByteArray[i] := Ord(LRandomTemp[i + 1]);                 <---   esta gerando erro aqui, pois o length do LRandom está menor
    Inc(i);
  end;

Para resolver eu alterei a linha while para --->   "while I < Length(LRandomTemp) do"

**Comment by viniciussanchez** [comment]
Você está usando a versão 1.0.7?
Qual a versão do Delphi que você está utilizando?

**Comment by Iaster** [comment]
estou usando o Delhpi 11.0     a versão do Bcrypt é a 0.1.7

**Comment by Iaster** [comment]
O meu é Delphi 11.0 e a versão do Bcrypt é a 1.0.7 mesmo.

 

 

Iaster

 

De: Vinicius Sanchez ***@***.***> 
Enviada em: terça-feira, 19 de abril de 2022 10:13
Para: viniciussanchez/bcrypt ***@***.***>
Cc: Iaster ***@***.***>; Author ***@***.***>
Assunto: Re: [viniciussanchez/bcrypt] Bcrypt "error": "Range check error" (Issue #5)

 

Você está usando a versão 1.0.7?
Qual a versão do Delphi que você está utilizando?

**Comment by andrewsbejatto** [comment]
Boa tarde, aqui comigo está dando o mesmo erro, estou usando Delphi 11.1 e última versão tbm desse projeto.
Fiz a modificação que o laster informou e deu certo!
